CREATE TABLE Extensiones
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(155) NULL,
	Descripcion VARCHAR(255) NULL,
	Estado VARCHAR(155) NULL,
	Ciudad VARCHAR(155) NULL,
	Direccion VARCHAR(255) NULL,
	Defecto TINYINT NOT NULL DEFAULT 0, -- 1 DEFETCO, 0 NO
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Carreras
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    Nombre VARCHAR(155) NULL, 
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE ExtensionCarreras
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    ExtensionId INT NOT NULL, 
    CarreraId INT NOT NULL, 
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_EXTENSIONES_ID FOREIGN KEY (ExtensionId) REFERENCES Extensiones (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_CARRERAS_ID FOREIGN KEY (CarreraId) REFERENCES Carreras (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Roles
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    Nombre VARCHAR(55) NULL, --Administrador / Bibliotecario / Estudiante / Docente / Directivo
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Politicas
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Tipo VARCHAR(15) NULL, --Header, Boton
    Nombre VARCHAR(155) NULL,
	Ruta VARCHAR(155) NULL,
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE RolPoliticas
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    RolId INT NOT NULL,
    PoliticaId INT NOT NULL
    CONSTRAINT FK_ROLPOLITICA_ID FOREIGN KEY (RolId) REFERENCES Roles (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT FK_POLITICA_ROL_ID FOREIGN KEY (PoliticaId) REFERENCES Politicas (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Usuarios
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	ExtensionId INT NOT NULL,
	RolId INT NOT NULL,
	Correo VARCHAR(255) NOT NULL UNIQUE,
    Contrasena VARCHAR(255) NOT NULL,
	Activo TINYINT NOT NULL DEFAULT 1,
	UltimoAcceso DATETIME NOT NULL DEFAULT GETDATE(),
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_EXTENSION_USUARIO_ID FOREIGN KEY (ExtensionId) REFERENCES Extensiones (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_ROL_USUARIO_ID FOREIGN KEY (RolId) REFERENCES Roles (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE DatosPersonales
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	UsuarioId INT NOT NULL UNIQUE,
	Cedula VARCHAR(25) NOT NULL UNIQUE,
    Nombres VARCHAR(255) NOT NULL,
    Apellidos VARCHAR(255) NOT NULL,
    FechaNacimiento VARCHAR(55) NOT NULL,
    Sexo VARCHAR(15) NOT NULL,
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_USUARIO_DP_ID FOREIGN KEY (UsuarioId) REFERENCES Usuarios (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE DatosAcademicos
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	UsuarioId INT NOT NULL UNIQUE,
	CarreraId INT NOT NULL,
	TipoIngreso VARCHAR(55) NOT NULL, -- Nacional / Internacional
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_USUARIO_DA_ID FOREIGN KEY (UsuarioId) REFERENCES Usuarios (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_USUARIO_CARRERA_ID FOREIGN KEY (CarreraId) REFERENCES Carreras (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Auditoria
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	UsuarioId INT NOT NULL,
    Tabla VARCHAR(15) NOT NULL,
    Accion VARCHAR(155) NOT NULL,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_USUARIO_AUDITORIA_ID FOREIGN KEY (UsuarioId) REFERENCES Usuarios (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Autores
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    Nombres VARCHAR(155) NOT NULL,
    Apellidos VARCHAR(155) NOT NULL,
    Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE TiposMateriales
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    Tipo VARCHAR(55) NULL, -- Libros / Tesis / Informes de pasantias / Servicio Comunitario / Proyecto de investigacion
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Editoriales
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    Nombre VARCHAR(255) NULL,
	Anio VARCHAR(25) NULL,
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Materiales
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	ExtensionId INT NOT NULL,
    TipoMaterialId INT NOT NULL,
	EditorialId INT NULL,
    AutorId INT NOT NULL,
    Cota VARCHAR(155) NOT NULL,
    Titulo VARCHAR(255) NOT NULL,
    Edicion VARCHAR(155) NULL,
    Estatus VARCHAR(25) NOT NULL, -- Activo / Inactivo / Desincorporado / En reparacion
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_TIPO_MATERIAL_ID FOREIGN KEY (TipoMaterialId) REFERENCES TiposMateriales (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_AUTOR_MATERIALES_ID FOREIGN KEY (AutorId) REFERENCES Autores (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_EXTENSION_ID FOREIGN KEY (ExtensionId) REFERENCES Extensiones (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_EDITORIAL_ID FOREIGN KEY (EditorialId) REFERENCES Editoriales (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE ReglasPrestamos
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TipoMaterialId INT NOT NULL,
    DiasLimites INT NOT NULL, -- 5 dias
    HorasLimites INT NOT NULL, -- 120 horas
    CantidadLimites INT NOT NULL, -- 3 es el limite de materiales por prestamo
    Mora DECIMAL NULL, -- Valor mora por tipo de material, puede ser recalculado por retarno de devolucion en Morosidad
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_REGLA_TIPO_MATERIAL_ID FOREIGN KEY (TipoMaterialId) REFERENCES TiposMateriales (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Prestamos
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ReglaPrestamoId INT NOT NULL,
    MaterialId INT NOT NULL,
    UsuarioId INT NOT NULL,
    Estatus VARCHAR(15) NOT NULL, -- Prestado / Devuelto
    FechaPrestamo DATETIME NOT NULL,
    FechaDevolucion DATETIME NULL,
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_PRESTAMOS_MATERIAL_ID FOREIGN KEY (MaterialId) REFERENCES Materiales (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FK_PRESTAMOS_USUARIO_ID FOREIGN KEY (UsuarioId) REFERENCES Usuarios (Id),
	CONSTRAINT FK_REGLA_PRESTAMO_ID FOREIGN KEY (ReglaPrestamoId) REFERENCES ReglasPrestamos (Id)
);

CREATE TABLE Morosidad
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    PrestamoId INT NOT NULL,
    Monto DECIMAL NOT NULL, -- Recalculado segun reglas de prestamo
    Estatus VARCHAR(15) NOT NULL, -- No cancelado / Cancelado
	Activo TINYINT NOT NULL DEFAULT 1,
	FechaCreado DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_PRESTAMOS_MORODIAD_ID FOREIGN KEY (PrestamoId) REFERENCES Prestamos (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);
