SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SPDatosAcademicosAddCommand]
	@UsuarioId INT = NULL,
	@CarreraId INT = NULL,
    @TipoIngreso VARCHAR(25) = NULL
AS
SET NOCOUNT ON;
BEGIN
	BEGIN TRY
		BEGIN
			DECLARE @SCOPEIDENTITY INT;
			INSERT INTO dbo.DatosAcademicos(UsuarioId, CarreraId, TipoIngreso)
			VALUES(@UsuarioId, @CarreraId, @TipoIngreso);
				SET @SCOPEIDENTITY = SCOPE_IDENTITY();
					SELECT @SCOPEIDENTITY AS Id
		END
	END TRY
		BEGIN CATCH
			SELECT ERROR_MESSAGE() AS ERROR,
				ERROR_NUMBER() AS ERROR_NRO
		END CATCH;
END
GO
